// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22oPmRh6005OATwFboayolgd8Yv_BiYw',
    appId: '1:80867449769:web:30cac4431effa0e63542b8',
    messagingSenderId: '80867449769',
    projectId: 'todo-notes-fcm',
    authDomain: 'todo-notes-fcm.firebaseapp.com',
    storageBucket: 'todo-notes-fcm.firebasestorage.app',
    measurementId: 'G-NYMSMRJWXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BieyKKUCCC7bg26b22rNVuSxCDpd6DI',
    appId: '1:80867449769:android:d3f65b8efaf997b43542b8',
    messagingSenderId: '80867449769',
    projectId: 'todo-notes-fcm',
    storageBucket: 'todo-notes-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7a0DWEOao3P9R-Aa8ur_gDbnCqoN9ios',
    appId: '1:80867449769:ios:8c8151428bed46673542b8',
    messagingSenderId: '80867449769',
    projectId: 'todo-notes-fcm',
    storageBucket: 'todo-notes-fcm.firebasestorage.app',
    iosBundleId: 'com.example.todoNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7a0DWEOao3P9R-Aa8ur_gDbnCqoN9ios',
    appId: '1:80867449769:ios:8c8151428bed46673542b8',
    messagingSenderId: '80867449769',
    projectId: 'todo-notes-fcm',
    storageBucket: 'todo-notes-fcm.firebasestorage.app',
    iosBundleId: 'com.example.todoNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC22oPmRh6005OATwFboayolgd8Yv_BiYw',
    appId: '1:80867449769:web:ac07cfc9876df2ef3542b8',
    messagingSenderId: '80867449769',
    projectId: 'todo-notes-fcm',
    authDomain: 'todo-notes-fcm.firebaseapp.com',
    storageBucket: 'todo-notes-fcm.firebasestorage.app',
    measurementId: 'G-W4TXKPYVTM',
  );
}
