import requests
import os
from dotenv import load_dotenv

def send_prompt_to_ai(prompt:str):
        

    load_dotenv()
    token = os.getenv("HF_TOKEN")

    url = "https://router.huggingface.co/v1/chat/completions"  #?  <-- URL For Api

    headers = {         
        "Authorization":  f"Bearer {token}",  #?  <--- Auth token 
        "Content-Type": "application/json"
    }

    #! Working model:  "deepseek-ai/DeepSeek-R1:fastest"   (It is a thinking model) 
    #! can test with these for short responses : "model": "deepseek-ai/DeepSeek-V3" , "model": "meta-llama/Llama-3.1-8B-Instruct"




    payload = {
        "model": "deepseek-ai/DeepSeek-V3",   # IMPORTANT: working model  , MODEL used
        "messages": [
            {"role": "user", "content": prompt}  #! Actual user prompt
        ],
        #  "max_tokens": 30   # 🔥 THIS controls output length
    }

    response = requests.post(url, headers=headers, json=payload)   #? API Call

    data = response.json()

    print(f"Status Code: {response.status_code}")
    print(data)
    if "error" in data:
        print("AI Error:", data["error"]["message"])
        return None  # don't crash
    content = data["choices"][0]["message"]["content"]   #? <--  Actual response
    return content

# Will give you a response like:
# {
#   "id": "...",   <---- this is the id of the response, you can use it to track the conversation
#   "object": "chat.completion",  <---- this is the type of the response
#   "created": ...,  <--- this is the timestamp of the response
#   "model": "...",  <--- this is the model used to generate the response
#   "choices": [...],  <--- this is the list of choices generated by the model, each choice has a "message" field which contains the generated message
#   "usage": {...}  <--- this is the usage information, it contains the number of tokens used for the prompt and the completion, and the total tokens used.
# }

# 🔥 5️⃣ choices (MOST IMPORTANT)
# "choices": [
#   {
#     "index": 0,
#     "message": {...},
#     "finish_reason": "stop"
#   }
# ]

# 👉 This is where the actual answer lives

# Inside message
# "message": {
#   "role": "assistant",
#   "content": "...",
# }
# 🔑 role
# "assistant" → AI reply
# "user" → your input
# "system" → system instruction (if used)
# 🔑 content

# This is the actual answer

# BUT in your case:

# <think>...</think>
# The capital of France is Paris

# 👉 Two parts:

# 🧠 1. <think>...</think>
# Model’s internal reasoning
# Usually hidden in production
# DeepSeek exposes it sometimes
# 💬 2. Actual answer
# The capital of France is Paris
# ⚠️ Important (for your app)

# You should strip <think> part before showing user.

# 🔑 finish_reason
# "finish_reason": "stop"

# Meaning:

# "stop" → completed normally
# "length" → cut due to token limit
# "error" → something went wrong