import json
from urllib import response

import requests
import os
from dotenv import load_dotenv

def send_prompt_to_ai(prompt: str):

    load_dotenv()
    token = os.getenv("HF_TOKEN")

    url = "https://router.huggingface.co/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "deepseek-ai/DeepSeek-V3",
        "messages": [
            {"role": "user", "content": prompt}
        ]
    }

    response = requests.post(
        url,
        headers=headers,
        json=payload
    )

    data = response.json()

    print(f"Status Code: {response.status_code}")
    print(data)

    if "error" in data:
        print("AI Error:", data["error"]["message"])
        return None

    import json

    content = data['choices'][0]['message']['content']

    # Remove markdown fences
    content = (
        content
        .replace("```json", "")
        .replace("```", "")
        .strip()
    )

    generated_notifications = json.loads(content)

    return generated_notifications

# Will give you a response like:
# {
#   "id": "...",   <---- this is the id of the response, you can use it to track the conversation
#   "object": "chat.completion",  <---- this is the type of the response
#   "created": ...,  <--- this is the timestamp of the response
#   "model": "...",  <--- this is the model used to generate the response
#   "choices": [...],  <--- this is the list of choices generated by the model, each choice has a "message" field which contains the generated message
#   "usage": {...}  <--- this is the usage information, it contains the number of tokens used for the prompt and the completion, and the total tokens used.
# }

# 🔥 5️⃣ choices (MOST IMPORTANT)
# "choices": [
#   {
#     "index": 0,
#     "message": {...},
#     "finish_reason": "stop"
#   }
# ]

# 👉 This is where the actual answer lives

# Inside message
# "message": {
#   "role": "assistant",
#   "content": "...",
# }
# 🔑 role
# "assistant" → AI reply
# "user" → your input
# "system" → system instruction (if used)
# 🔑 content

# This is the actual answer

# BUT in your case:

# <think>...</think>
# The capital of France is Paris

# 👉 Two parts:

# 🧠 1. <think>...</think>
# Model’s internal reasoning
# Usually hidden in production
# DeepSeek exposes it sometimes
# 💬 2. Actual answer
# The capital of France is Paris
# ⚠️ Important (for your app)

# You should strip <think> part before showing user.

# 🔑 finish_reason
# "finish_reason": "stop"

# Meaning:

# "stop" → completed normally
# "length" → cut due to token limit
# "error" → something went wrong